# Generated by Django 5.0.14 on 2025-05-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Claim_No', models.CharField(max_length=100, unique=True, verbose_name='Shipment Number')),
                ('Branch', models.CharField(choices=[('ATL', 'ATL'), ('CMU', 'CMU'), ('CON', 'CON'), ('DOR', 'DOR'), ('HEC', 'HEC'), ('HNL', 'HNL'), ('HOU', 'HOU'), ('ICS', 'ICS'), ('IMP', 'IMP'), ('JFK', 'JFK'), ('LAX', 'LAX'), ('LCL', 'LCL'), ('ORD', 'ORD'), ('PPG', 'PPG')], max_length=3)),
                ('Brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('Claimant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Claimant Name')),
                ('Intent_To_Claim', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True, verbose_name='Intent To Claim')),
                ('Intend_Claim_Date', models.DateField(blank=True, null=True, verbose_name='Intent To Claim Date')),
                ('Formal_Claim_Received', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True, verbose_name='Formal Claim')),
                ('Formal_Claim_Date_Received', models.DateField(blank=True, null=True, verbose_name='Formal Claim Date')),
                ('Claimed_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Value')),
                ('Amount_Paid_By_Carrier', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid By Carrier')),
                ('Amount_Paid_By_Awa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid By ISCM/AWA')),
                ('Amount_Paid_By_Insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid By Insurance')),
                ('Total_Savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Savings')),
                ('Financial_Exposure', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Financial Exposure')),
                ('Settlement_Status', models.CharField(blank=True, choices=[('SETTLED', 'Settled'), ('NOT_SETTLED', 'Not Settled'), ('PARTIAL', 'Partially Settled')], max_length=15, null=True, verbose_name='Settled or Not Settled')),
                ('Status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='OPEN', max_length=15, verbose_name='Status')),
                ('Closed_Date', models.DateField(blank=True, null=True, verbose_name='Closed Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='main.client')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
