# Generated by Django 5.0.14 on 2025-06-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Claim_No',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Shipment Number'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_id'], name='main_client_client__8da953_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='main_client_name_c070b5_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-created_at'], name='main_client_created_850ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['client', 'Claim_No'], name='main_shipme_client__c50d11_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['Claim_No'], name='main_shipme_Claim_N_a03a13_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['Status'], name='main_shipme_Status_7826b6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['Settlement_Status'], name='main_shipme_Settlem_03f867_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['-created_at'], name='main_shipme_created_99d9fc_idx'),
        ),
    ]
