# Generated by Django 5.0.14 on 2025-06-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_client_id_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='client_reference',
            field=models.CharField(blank=True, help_text='Auto-generated client-specific reference (e.g., ClientName-1-20250601)', max_length=50, null=True, verbose_name='Client Reference'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Claim_No',
            field=models.CharField(max_length=100, unique=True, verbose_name='Shipment Number'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['client_reference'], name='main_shipme_client__85a5d7_idx'),
        ),
    ]
