# Generated by Django 5.1.7 on 2025-09-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shipment_client_reference_alter_shipment_claim_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='claim_id',
            field=models.CharField(blank=True, help_text='Auto-generated unique claim identifier (e.g., CLM000001, CLM000002)', max_length=20, null=True, unique=True, verbose_name='Claim ID'),
        ),
    ]
